export const NEW_SUBSCRIBE_REQUEST = "NEW_SUBSCRIBE_REQUEST";
export const NEW_SUBSCRIBE_SUCCESS = "NEW_SUBSCRIBE_SUCCESS";
export const NEW_SUBSCRIBE_RESET = "NEW_SUBSCRIBE_RESET";
export const NEW_SUBSCRIBE_FAIL = "NEW_SUBSCRIBE_FAIL";

export const GET_SUBSCRIBE_REQUEST = "GET_SUBSCRIBE_REQUEST";
export const GET_SUBSCRIBE_SUCCESS = "GET_SUBSCRIBE_SUCCESS";
export const GET_SUBSCRIBE_FAIL = "GET_SUBSCRIBE_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
